name: Robot Framework Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Robot Framework tests
        run: |
          docker run --rm -v $GITHUB_WORKSPACE:/github/workspace ppandiyan/robotframework robot --outputdir /github/workspace/testOutput /github/workspace/test.robot

      # 部署测试报告到 GitHub Pages 分支
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./testOutput
          publish_branch: gh-pages
