name: Robot Framework Test

on:
  push:
    branches:
      - main  # 或者其他你希望触发工作流的分支
  pull_request:
    branches:
      - main  # 或者其他你希望触发工作流的分支

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker 环境
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 运行 Robot Framework 测试
      - name: Run Robot Framework tests
        uses: docker://ppandiyan/robotframework
        with:
          args: --outputdir testOutput test.robot

      # 上传测试输出作为工件
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: testOutput
          path: testOutput